version: '3,8'

services:
  mn_category:
    container_name: 'mn_category'
    image: postgres:15.2-alpine3.17
    restart: unless-stopped
    environment:
      POSTGRES_DB: mn_category
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    ports:
      - 5432:5432
    expose:
      - 5432
    command: -p 5432