version: '3.8'

services:
  mn_category:
    container_name: 'mn_category'
    image: postgres:15.2-alpine3.17
    restart: unless-stopped
    environment:
      POSTGRES_DB: mn_category
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
      POSTGRES_LISTEN_ADDRESSES: 0.0.0.0
    ports:
      - "5432:5432"
    expose:
      - "5432"
    command: -c listen_addresses=0.0.0.0 -p 5432

  microservicio-categorias:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - mn_category
